# Generated by Django 5.2.11 on 2026-02-06 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetup', '0015_project_is_active'),
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='rera_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('rera_no', ''), _negated=True), fields=('belongs_to', 'rera_no'), name='uniq_project_rera_per_admin'),
        ),
    ]
