# Generated by Django 5.2.3 on 2025-12-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanage', '0004_leadsource_for_walkin'),
        ('salelead', '0037_alter_salesleadprofessionalinfo_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadopportunity',
            name='source_system',
            field=models.CharField(choices=[('META', 'Meta / Facebook Ads'), ('GOOGLE_SHEET', 'Google Sheet'), ('GOOGLE_ADS', 'Google Ads'), ('WEB_FORM', 'Website Form'), ('PORTAL', 'Property Portal'), ('WHATSAPP', 'WhatsApp'), ('CHATBOT', 'Chatbot'), ('CALLING', 'Calling Data Upload'), ('OTHER', 'Other / Manual Import'), ('DIGITAL', 'Digital'), ('DIRECT', 'Direct/Walk-In'), ('CHANNER_PARTNER', 'Channel Partner')], default='OTHER', help_text='From where this opportunity came (Meta, Sheet, Web, Portal, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadopportunity',
            name='status',
            field=models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged'), ('RINGING_BUSY', 'RINGIING/BUSY'), ('DETAILS', 'DETAILS SHARED'), ('SV_LINEUP', 'SV LINE UP'), ('SV_DONE', 'SV DONE'), ('RV_DONE', 'RV DONE'), ('NOT_INTERESTED', 'NOT INTERESTED'), ('LOW_BUDGET', 'LOW BUDGET'), ('READY_TO_MOVE_IN', 'READY TO MOVE IN'), ('NEAR_POSSESSION', 'NEAR POSSESSION'), ('OTHERS', 'OTHERS')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadopportunitystatusconfig',
            name='code',
            field=models.CharField(choices=[('NEW', 'New (not reviewed)'), ('IN_REVIEW', 'In Review'), ('CONVERTED', 'Converted to Lead'), ('JUNK', 'Marked as Junk'), ('DUPLICATE', 'Duplicate / Merged'), ('RINGING_BUSY', 'RINGIING/BUSY'), ('DETAILS', 'DETAILS SHARED'), ('SV_LINEUP', 'SV LINE UP'), ('SV_DONE', 'SV DONE'), ('RV_DONE', 'RV DONE'), ('NOT_INTERESTED', 'NOT INTERESTED'), ('LOW_BUDGET', 'LOW BUDGET'), ('READY_TO_MOVE_IN', 'READY TO MOVE IN'), ('NEAR_POSSESSION', 'NEAR POSSESSION'), ('OTHERS', 'OTHERS')], help_text='Status code stored on LeadOpportunity.status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesleadprofessionalinfo',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='leadmanage.designation'),
        ),
    ]
